language: cpp
compiler: gcc

os: linux
dist: xenial
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake

before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential binutils-gold libsdl2 libsdl2-dev libfreetype6-dev freeglut3 freeglut3-dev libglew2.0 libglew-dev libglu1-mesa-dev mesa-common-dev libglm-dev

script:
  - export CC=/usr/bin/gcc-7
  - export CXX=/usr/bin/g++-7
  - cmake --version
  - cmake CMakeLists.txt
  - cmake  --build .